---
ID: "06f353cc-5aee-4ed9-b2b9-63dc9efe8e2f"
Parent: "cb4d634a-409f-4e32-99db-e51dd3675116"
Template: "9f2e6785-ae61-4ae4-837e-ffed3b217200"
Path: "/sitecore/content/Zodiac/ZodiacManual/home/installed-features/things-you-need-to-configure"
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 600
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "1a61ece0-2b10-458c-81c7-1e080222da7b"
      Hint: Browser Title
      Value: Things You Need to Configure
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20201001T142812Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "9035f3e3-df0f-4446-af7b-f4c048fb3f52"
    - ID: "94016f9f-ff2c-4192-9a9f-8fd1d89b1f13"
      Hint: Heading
      Value: Things You Need to Configure
    - ID: "a8fad4b5-f582-4b63-9031-8fa8ea8b6d06"
      Hint: Navigation Title
      Value: Things You Need to Configure
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\rcabral
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20201001T142813Z
