---
ID: "06f353cc-5aee-4ed9-b2b9-63dc9efe8e2f"
Parent: "cb4d634a-409f-4e32-99db-e51dd3675116"
Template: "9f2e6785-ae61-4ae4-837e-ffed3b217200"
Path: "/sitecore/content/Zodiac/ZodiacManual/home/installed-features/things-you-need-to-configure"
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 600
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Type: Layout
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{CA0270A6-4EA1-4090-9BF9-8E740EF68815}"
              p:after="p[@uid='{E941B0CF-5A49-49F6-B29B-D9B3BEA2D675}']"
              s:ds="{404A4ACD-980D-4EEC-90AF-C95D538BFA6F}"
              s:id="{C52BD435-3CB6-4851-A77E-22875C6226A7}"
              s:ph="/Rows/AuxiliaryComponents-{6AFD798C-4B3A-4219-95A8-1D77749DEF44}-0" />
            <r
              uid="{7E837E8B-2ACA-4519-99EC-0C92525474AD}"
              p:after="r[@uid='{CA0270A6-4EA1-4090-9BF9-8E740EF68815}']"
              s:ds="{3A58EE7F-3DAA-4850-8E27-7DEC3311EB1C}"
              s:id="{5B77B275-CCC9-4627-80FC-4F57E9D1DE34}"
              s:ph="/Rows/ContentSections-{6AFD798C-4B3A-4219-95A8-1D77749DEF44}-0" />
            <r
              uid="{E8A1B66F-9D6B-42A3-A77B-61B67EC50607}"
              s:ph="Rows" />
            <r
              uid="{6AFD798C-4B3A-4219-95A8-1D77749DEF44}"
              p:after="r[@uid='{E8A1B66F-9D6B-42A3-A77B-61B67EC50607}']"
              s:id="{D42EC9EB-E081-446C-B29F-36F6C01D24EC}"
              s:ph="Rows" />
            <r
              uid="{79053113-DC56-4A41-8638-13CF52CF8DFC}"
              p:after="r[@uid='{6AFD798C-4B3A-4219-95A8-1D77749DEF44}']"
              s:ds="{4D80FA6C-8E20-4551-AAD1-E1D3DD369FF8}"
              s:id="{6E0ABACE-DDE6-45B8-8681-CA8354A5D90D}"
              s:ph="Rows" />
            <r
              uid="{9ACB6FDD-8AD2-4F62-B064-C6CA32302ADE}"
              p:after="r[@uid='{79053113-DC56-4A41-8638-13CF52CF8DFC}']"
              s:ds="{4614B551-6122-4378-8699-2321362744DA}"
              s:id="{6E0ABACE-DDE6-45B8-8681-CA8354A5D90D}"
              s:ph="Rows" />
            <r
              uid="{ED526EB5-93A4-45B5-AC69-E1EE81992270}"
              p:after="r[@uid='{9ACB6FDD-8AD2-4F62-B064-C6CA32302ADE}']"
              s:ds="{9ED28E2E-D2C1-4A4F-8C10-C58746D4ABF2}"
              s:id="{6E0ABACE-DDE6-45B8-8681-CA8354A5D90D}"
              s:ph="Rows" />
            <r
              uid="{57FE8363-9745-4BD3-A7BF-EF5F46305A72}"
              p:after="*[1=2]"
              s:ds="{5569364C-7684-43B1-94AE-E4A5F66A53D8}"
              s:id="{6E0ABACE-DDE6-45B8-8681-CA8354A5D90D}"
              s:ph="Rows" />
          </d>
        </r>
    - ID: "1819e6ed-34fb-4f4b-8c28-6d55382bcd9f"
      Hint: Intro Copy
      Value: Most Zodiac features are enabled by default, a few need your attention to either turn them on, or improve their accuracy.
    - ID: "1a61ece0-2b10-458c-81c7-1e080222da7b"
      Hint: Browser Title
      Value: Things You Need to Configure
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20201001T142812Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c74f65d0-f32f-489e-9296-d2201c6d6d3c"
    - ID: "911a2a84-64b8-4113-ab31-4f519ec3ac84"
      Hint: Copy
      Value: |
        <p>Because Zodiac doesn't know about your Project Layer, a few things need to be set up during your project build to get the most out of Zodiac, all of these are Site-specific:</p>
        <ul>
            <li>Project-Specific Page Templates</li>
            <li>Project-Specific Layouts &amp; Sublayouts</li>
            <li>Project-Specific Media Library folders</li>
            <li>Project-Specific Site Config (hostnames, URL generation, etc...)</li>
            <li>Site Specific 404 Pages</li>
            <li>Custom Sitemap.XML generation (if necessary)</li>
            <li>Static Navigation scaffolding for the new Site.</li>
            <li>Placeholder Settings</li>
        </ul>
    - ID: "94016f9f-ff2c-4192-9a9f-8fd1d89b1f13"
      Hint: Heading
      Value: Things You Need to Configure
    - ID: "a8fad4b5-f582-4b63-9031-8fa8ea8b6d06"
      Hint: Navigation Title
      Value: Things You Need to Configure
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\rcabral
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20201111T185025Z
