---
ID: "9e08ac1f-f1ba-4833-ab48-9ddc4fe4e6cd"
Parent: "87f208ca-597d-4b6e-979e-836b4e643442"
Template: "9f2e6785-ae61-4ae4-837e-ffed3b217200"
Path: "/sitecore/content/Zodiac/ZodiacManual/home/setting-up-a-new-site/configure-iis"
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 200
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Type: Layout
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{E8A1B66F-9D6B-42A3-A77B-61B67EC50607}"
              s:ph="Rows" />
            <r
              uid="{FD5DE431-B533-4662-87DB-0559F38DA7BA}"
              p:after="*[1=2]"
              s:ds="{77F3E020-B1F2-4338-8B3F-39D6CA8C4877}"
              s:id="{6E0ABACE-DDE6-45B8-8681-CA8354A5D90D}"
              s:ph="Rows" />
          </d>
        </r>
    - ID: "1819e6ed-34fb-4f4b-8c28-6d55382bcd9f"
      Hint: Intro Copy
      Value: <p>Make sure requests are going to be passed to Sitecore</p>
    - ID: "1a61ece0-2b10-458c-81c7-1e080222da7b"
      Hint: Browser Title
      Value: Configure IIS
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20201105T193047Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1041315d-e4b3-4137-823c-78319db62449"
    - ID: "911a2a84-64b8-4113-ab31-4f519ec3ac84"
      Hint: Copy
      Value: |
        <p>If you're reading this document then you already have a working Sitecore installation declared in IIS. We're going to keep this step focused on your "local" Sitecore installation, but remember that any changes you make to your local IIS installation will require similar changes in other environments. Keep in mind that these steps are "standard" Sitecore and should be equivalent to any Sitecore documentation.</p>
        <p>To support your next site:</p>
        <ul>
            <li>Locate this website in your IIS console</li>
            <li>Edit the Bindings and add a new Binding for the desired hostname of your new site.</li>
            <li>If you're using TLS (default in Sitecore 10) you should select port 443 as the port to bind.</li>
            <li>We are going to assume you already have a local trusted certificate for this installation. For other environment you may need to reference an appropriate SSL certificate.</li>
            <li>Ensure that your new hostname resolves via DNS - This may mean modifying your hosts file to include the new hostname.</li>
        </ul>
        <h3>A note on HTTPS/TLS/SSL</h3>
        <p>The Sitecore 10 installation process creates a local self-signed certificate for your installation's first hostname. You may need to create an additional certificate for your new hostname in order for your browser to successfully load your new site. <a rel="noopener noreferrer" href="https://dotnetcodetips.com/Tip/90/Create-a-self-signed-certificate-with-PowerShell-New-SelfSignedCertificate-or-Makecertexe" target="_blank">New self-signed certificates (for development use) are easy to create with PowerShell.</a></p>
        <p><a rel="noopener noreferrer" href="https://dotnetcodetips.com/Tip/90/Create-a-self-signed-certificate-with-PowerShell-New-SelfSignedCertificate-or-Makecertexe" target="_blank"></a>You may want to bind your new hostname to Port 80 as well as Port 443. Zodiac ships with a UrlRewrite rule that will take unencrypted requests and permanent redirect them to their encrypted equivalent. Some browsers do not assume "https" in the URL. Having both ports bound prevents "not supported" errors coming back from IIS.</p>
        <ul>
        </ul>
        <h3>Using Docker Containers?</h3>
        <p>If you're using Docker Containers for development, the process for binding the new hostname and the ports in play may be different. Refer to the Sitecore documentation.</p>
    - ID: "94016f9f-ff2c-4192-9a9f-8fd1d89b1f13"
      Hint: Heading
      Value: Configure IIS
    - ID: "a8fad4b5-f582-4b63-9031-8fa8ea8b6d06"
      Hint: Navigation Title
      Value: Configure IIS
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\rcabral
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20201111T183325Z
