---
ID: "6e9eaeb3-ee81-4413-a5cc-adb1a6e1682c"
Parent: "87f208ca-597d-4b6e-979e-836b4e643442"
Template: "a6dbf438-1236-4182-bf61-fac8a221f81f"
Path: "/sitecore/content/Zodiac/ZodiacManual/home/setting-up-a-new-site/link-provider-configuration"
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "1a61ece0-2b10-458c-81c7-1e080222da7b"
      Hint: Browser Title
      Value: Link Provider Configuration
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200811T172341Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "8ea0421a-9558-40d7-bd59-224f26f97386"
    - ID: "94016f9f-ff2c-4192-9a9f-8fd1d89b1f13"
      Hint: Heading
      Value: Link Provider Configuration
    - ID: "a8fad4b5-f582-4b63-9031-8fa8ea8b6d06"
      Hint: Navigation Title
      Value: Link Provider Configuration
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\rcabral
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20200922T175437Z
