---
ID: "ef8d2063-36e7-4d84-8a76-9ac2aafc2636"
Parent: "9e05384a-518f-4115-a1f0-980581437b6c"
Template: "547a79db-25a0-414d-ab7a-589e0e7d7511"
Path: "/sitecore/content/Zodiac/ZodiacManual/home/setting-up-a-new-site/visual-studio-setup/_subcontent/App_Config Folder"
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "0b674bf0-d756-48a7-a363-53f5ad334857"
      Hint: Caption
      Value: <p>The Website project is the only valid location for App_Config in a Zodiac solution.</p>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20201109T181414Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "4d70eb8a-e0f3-406a-b1f4-b6deae02b823"
    - ID: "9f337325-e776-41d5-9a15-ff017e501d5e"
      Hint: View Full Size In Modal
      Type: Checkbox
      Value: 0
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\rcabral
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20201109T181606Z
    - ID: "f4c8fdba-d80f-4612-b1c7-4a9a9c7c0bfd"
      Hint: Full Size Image
      Value: |
        <image mediaid="{246066E8-7C5B-4BFF-AB21-913E316711BF}" />
    - ID: "fb51681e-4d1e-4eb8-b3ce-f78af3d5013f"
      Hint: Heading
      Value: App_Config Folder
