---
ID: "9a433a51-614e-45d9-b0fc-66ebd5e3ddbb"
Parent: "9e05384a-518f-4115-a1f0-980581437b6c"
Template: "7bca1a6d-2e40-4265-8575-abce3705555c"
Path: "/sitecore/content/Zodiac/ZodiacManual/home/setting-up-a-new-site/visual-studio-setup/_subcontent/Create the Project Config Folder"
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "0616d4fc-880f-4cc1-a359-4ccc88fc37ec"
      Hint: Copy
      Value: |
        <p>After opening the Visual Studio solution, navigate to the "Website" project and open the <code>/App_Config/Include/Project</code> folder.</p>
        <p>we recommend Copying the "ProjectName" folder and renaming it to match your Site node. This provides you with an example site config file which should be renamed to <code>[your site node name].Site.config</code></p>
    - ID: "19411c92-adbe-4f6b-93a2-ffc01d5b45ca"
      Hint: Heading
      Value: Create the Project Config Folder
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20201109T160148Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "93cbec91-ab7d-47ad-910a-59b4cbd7168f"
    - ID: "a2645c0c-2cea-4c66-a09b-31f6e6271a7a"
      Hint: Trailing Link
      Value: 
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\rcabral
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20201109T180842Z
