---
ID: "8b69c164-c1d0-4fc7-8788-43f49f1fe6bc"
Parent: "9e05384a-518f-4115-a1f0-980581437b6c"
Template: "547a79db-25a0-414d-ab7a-589e0e7d7511"
Path: "/sitecore/content/Zodiac/ZodiacManual/home/setting-up-a-new-site/visual-studio-setup/_subcontent/Example Site Configuration File"
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "0b674bf0-d756-48a7-a363-53f5ad334857"
      Hint: Caption
      Value: <p>After copying the example project folder, your solution should resemble this one.</p>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20201109T182208Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f0158a29-17d5-44bf-a26a-ef92a016d3d4"
    - ID: "9f337325-e776-41d5-9a15-ff017e501d5e"
      Hint: View Full Size In Modal
      Type: Checkbox
      Value: 0
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\rcabral
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20201109T182319Z
    - ID: "f4c8fdba-d80f-4612-b1c7-4a9a9c7c0bfd"
      Hint: Full Size Image
      Value: |
        <image mediaid="{B0173667-DCEC-4869-92CA-904D3267B302}" />
    - ID: "fb51681e-4d1e-4eb8-b3ce-f78af3d5013f"
      Hint: Heading
      Value: Example Site Configuration File
