---
ID: "2d4e7fd1-d1c9-430c-a649-c3d881bf3546"
Parent: "d03a7c5a-f775-42c4-b60e-1028572b0b31"
Template: "547a79db-25a0-414d-ab7a-589e0e7d7511"
Path: "/sitecore/content/Zodiac/ZodiacManual/home/rendering-tutorials/your-first-rendering/_subcontent/Semantic Placeholder Settings"
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "0b674bf0-d756-48a7-a363-53f5ad334857"
      Hint: Caption
      Value: <p>Store abstract Placeholder rules by Feature.</p>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200930T194541Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "8900e260-af5e-41d8-91cf-b95e89fc743a"
    - ID: "9f337325-e776-41d5-9a15-ff017e501d5e"
      Hint: View Full Size In Modal
      Type: Checkbox
      Value: 0
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\rcabral
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20200930T194709Z
    - ID: "f4c8fdba-d80f-4612-b1c7-4a9a9c7c0bfd"
      Hint: Full Size Image
      Value: |
        <image mediaid="{AD6A8497-8269-4726-B82D-9DFA49F7F564}" />
    - ID: "fb51681e-4d1e-4eb8-b3ce-f78af3d5013f"
      Hint: Heading
      Value: Semantic Placeholder Settings
