---
ID: "77f3e020-b1f2-4338-8b3f-39d6ca8c4877"
Parent: "334dc80e-5b68-49c8-b69f-8c127b56b03b"
Template: "7bca1a6d-2e40-4265-8575-abce3705555c"
Path: "/sitecore/content/Zodiac/ZodiacManual/home/setting-up-a-new-site/configure-iis/_subcontent/Test your Configuration"
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "0616d4fc-880f-4cc1-a359-4ccc88fc37ec"
      Hint: Copy
      Value: |
        <p>Try logging out of Sitecore and accessing your new hostname in a browser. </p>
        <p>The default Sitecore home page should load.</p>
        <p>If you deleted the default page, you may get a 404 or Layout Not Found error.</p>
        <p>We'll create valid Items in the next step.</p>
    - ID: "19411c92-adbe-4f6b-93a2-ffc01d5b45ca"
      Hint: Heading
      Value: Test your Configuration
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20201111T183100Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "49283d62-d7be-477f-bf4d-b59e7289a8c0"
    - ID: "a2645c0c-2cea-4c66-a09b-31f6e6271a7a"
      Hint: Trailing Link
      Value: |
        <link linktype="internal" text="Next: Content Tree Setup" querystring="" target="" id="{3DEB18F7-A052-4054-A62D-E15F40ACC82B}" />
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\rcabral
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20201111T183308Z
